spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: system
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
